#pragma once

#include "numathap/config/MathAdapter.hpp"
#include "numathap/core/Context.hpp"
#include "numathap/core/Value.hpp"
#include "numathap/math/MathNode.hpp"

namespace numathap::backend {

/**
 * @brief Evaluates a prepared mathematical AST.
 *
 * The Evaluator executes the semantic Math-AST generated by the
 * MathAstBuilder and prepared by the Orchestrator.
 *
 * The Evaluator does not implement mathematical functions directly.
 * Function calls and constants are delegated to MathAdapter.
 */
class Evaluator {
   public:

    /**
     * @brief Creates an evaluator.
     *
     * @param context Variable resolution context.
     * @param adapter Mathematical library adapter.
     */
    Evaluator(
        const core::Context& context,
        const config::MathAdapter& adapter);


    /**
     * @brief Evaluates a Math-AST.
     *
     * @param node Root node of the AST.
     *
     * @return Result value.
     */
    [[nodiscard]]
    core::Value evaluate(
        const math::MathNode& node) const;


   private:

    /**
     * @brief Recursively evaluates a MathNode.
     */
    [[nodiscard]]
    core::Value evaluateNode(
        const math::MathNode& node) const;


    const core::Context& context_;
    const config::MathAdapter& adapter_;
};


} // namespace numathap::backend