#pragma once

#include "numathap/config/MathAdapter.hpp"
#include "numathap/core/Context.hpp"
#include "numathap/core/Value.hpp"
#include "numathap/math/MathNode.hpp"

namespace numathap::backend {

/**
 * @brief Evaluates a prepared mathematical AST.
 *
 * The Evaluator executes the semantic Math-AST generated by the
 * MathAstBuilder and prepared by the Orchestrator.
 *
 * The Evaluator does not implement mathematical functions directly.
 * Function calls and constants are delegated to MathAdapter.
 */
class Evaluator {
   public:
    /**
     * @brief Creates an evaluator.
     *
     * @param adapter Mathematical library adapter.
     */
    explicit Evaluator(const config::MathAdapter& adapter);

    void prepare(math::MathNodePtr preparedAst);

    [[nodiscard]]
    core::Value calc(const core::Context& context) const;

   private:
    /**
     * @brief Recursively evaluates a MathNode.
     */
    [[nodiscard]]
    core::Value evaluateNode(const math::MathNode& node,
                             const core::Context& context) const;

    math::MathNodePtr preparedAst_;

    const config::MathAdapter& adapter_;
};

}  // namespace numathap::backend