#pragma once

#include "numathap/parser/ast/Node.hpp"

namespace numathap::orchestration {

/**
 * @brief Coordinates preparation stages applied to an AST.
 *
 * The Orchestrator receives an AST generated by the Parser and applies
 * optional transformation stages before the expression is processed
 * by a backend.
 *
 * Initially, the Orchestrator returns the original AST unchanged.
 * Future implementations may include simplification, normalization,
 * optimization, or other preparation steps.
 */
class Orchestrator {
   public:
    /**
     * @brief Prepare an AST for backend processing.
     *
     * @param root Root node of the AST.
     * @return Prepared AST.
     */
    ast::NodePtr prepare(ast::NodePtr root);
};

}  // namespace numathap::orchestration