name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build-cpp:
    uses: ./.github/workflows/cpp-release.yml
    permissions:
      contents: read

  build-python:
    uses: ./.github/workflows/python-package.yml
    permissions:
      contents: read

  publish-pypi:
    name: Publish Python package to PyPI
    needs:
      - build-python

    runs-on: ubuntu-latest

    environment: pypi

    permissions:
      id-token: write

    steps:
      - name: Download Python wheel
        uses: actions/download-artifact@v4
        with:
          name: python-wheel
          path: dist
      - name: List Python distributions
        run: |
          find dist -type f -print

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  create-release:
    needs:
      - build-cpp
      - build-python

    runs-on: ubuntu-latest

    steps:

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true

      - name: List release artifacts
        run: |
          find release-assets -type f -print

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/*
          generate_release_notes: true